<div class="owl-carousel owl-theme home-page-carosel">
	<?php for($i = 1;$i <=2 ;$i++): ?>
		<div class="item">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home-page-carosel-img-'.$i.'')->toHtml();?>
			<div class="item-content">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home-page-carosel-text-'.$i.'')->toHtml();?>
				<button>
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home-page-carosel-button-'.$i.'')->toHtml();?>
				</button>
			</div>
		</div>
	<?php endfor; ?>    
</div>



<script>
    require([
        'jquery',
        'owlCarousel'
        ], function ($) {
            $(document).ready(function() {
                var owl = $('.home-page-carosel');
                owl.owlCarousel({
                    items: 1,
                    loop: true,
                    // autoplay: true,
                    // autoplayTimeout: 1000,
                    autoplayHoverPause: true,
                    dots:false,
                    nav: false

                });
            });
        });
</script>